name: Continous Integration and Deployment
on: 
  push:
    branches: 
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code 
        uses: actions/checkout@v3.3.0

      - name: SetUp DotNet  
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name : Restore Dependencies
        run : dotnet restore

      - name : Build app
        run : dotnet build -c Release --no-restore
       
      - name : Run Automated Test
        run : dotnet test -c Release --no-build 